CREATE TABLE IF NOT EXISTS List(
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(200) NOT NULL,
updatedate VARCHAR(10) NOT NULL,
orderno INT NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Context(
id INT NOT NULL AUTO_INCREMENT,
fetchtime DATETIME NOT NULL,
PRIMARY KEY(id)
);